<?php

namespace PHPSC\UltraBlog\Repository\ORM;

use Doctrine\ORM\EntityRepository;
use PHPSC\UltraBlog\Repository\PostRepositoryInterface;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository implements PostRepositoryInterface {

    public function findLatestThree() {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select(['p']);
        $qb->from($this->getEntityName(), "p");
        $qb->orderBy("p.createdAt", "DESC");
        $qb->setMaxResults(3);
        return $qb->getQuery()->getResult();
    }

}
